name: env_counterfactuals_nlp
channels:
  - defaults
dependencies:
  - python=3.9.7
  - pip
  - conda-forge::gdown
  - ipykernel=6.4.1
  - numpy=1.20.3
  - pandas=1.3.4
  - matplotlib=3.4.3
  - ipywidgets
  - pytorch::pytorch=1.10.1
  - cudatoolkit=11.3
  - conda-forge::transformers=4.15.0
  - scipy=1.7.3
  - spacy=3.2.1
  - nltk=3.7
  - conda-forge::sentence-transformers=2.0.0
  - ipykernel
  - conda-forge::more-itertools=8.12.0
  - conda-forge::sentencepiece=0.1.96
  - statsmodels
  - seaborn
  - pip:
      - transformers-interpret==0.5.2
  
